apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otel-demo.name" . }}-otel-collector-sidecar-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
data:
  {{ (.Files.Glob "otel-collector-sidecar/*.yaml").AsConfig | nindent 2 }}
