receivers:
  filelog:
    include: [ /logs/*.log ]
    operators:
      - type: json_parser
        if: body matches "^{.*}$"
        timestamp:
          parse_from: attributes.timestamp
          layout: '%Y-%m-%dT%H:%M:%S.%fZ'
        severity:
          parse_from: attributes.severity
        message:
          parse_from: attributes.message
      - type: copy
        from: attributes.msg
        to: body

processors:
  resource:
    attributes:
      - key: service.instance.id
        from_attribute: k8s.pod.uid
        action: insert
      - key: service.name
        value: "${OTEL_SERVICE_NAME}"
        action: insert

exporters:
  otlp:
    endpoint: "http://${OTEL_COLLECTOR_NAME}:4317"
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [ filelog ]
      processors: [ resource ]
      exporters: [ otlp ]
