receivers:
  filelog:
    include: [/logs/*.log]
    operators:
      - type: json_parser
        timestamp:
          parse_from: attributes.timestamp
          layout: '%Y-%M-%DT%HH:%MM:%SS%Z'
        severity:
          parse_from: attributes.severity
        message:
          parse_from: attributes.message

exporters:
  otlp:
    endpoint: "http://opentelemetry-demo-otelcol:4317"
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [otlp]
