receivers:
  filelog:
    include:
      - /logs/*.log
    start_at: beginning
    operators:
      - type: regex_parser
        regex: '^(?P<timestamp>\S+)\s+(?P<level>[A-Z]+)\s+(?P<message>.*)$'
        timestamp:
          parse_from: timestamp
          format: '%Y-%m-%dT%H:%M:%S'

exporters:
  otlp:
    endpoint: "http://opentelemetry-demo-otelcol:4317"
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [otlp]
